return {
	coins = 0,
	luminite = 0,
	xp = 0,

	inventory = {
		pickaxes = { "rusty" },
		sifters = { "basic" },
		loot = {},
		equipment = {},
	},
	equipped = {
		pickaxe = "rusty",
		sifter = "basic",
		equipment = {},
	},
	quests = {},
	sifter_contains = {},

	statistics = {
		found_loot = {}, -- ["loot_name"] = {count = x, largest = y}
	},

	settings = {
		music_volume = 0.5,
		sfx_volume = 0.5,
	},
}
